version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - TZ=${TZ}
      - RAILS_ENV=development
      - BUCKY_DB_NAME=bucky_development
    depends_on:
      - db