version: 2
jobs:
  rails_best_practices:
    docker:
      - image: circleci/ruby:2.7.2-node
    steps:
      - checkout
      - restore_cache:
          key: rails-demo-{{ checksum "Gemfile" }}
      - run: bundle install --path vendor/bundle --with test
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run: bundle exec rails_best_practices -f html
      - store_artifacts:
          path: rails_best_practices_output.html
  rubocop:
    docker:
      - image: circleci/ruby:2.7.2-node
    steps:
      - checkout
      - run: gem install rubocop
      - run: rubocop -f html --out report.html
      - store_artifacts:
          path: report.html

workflows:
  version: 2
  test_and_static_analysis:
    jobs:
      - rails_best_practices
      - rubocop